global:
  resolve_timeout: 5m

route:
  receiver: webhook-dev
  group_by: ["alertname", "job"]
  group_wait: 10s
  group_interval: 30s
  repeat_interval: 2m

receivers:
  - name: webhook-dev
    webhook_configs:
      - url: "http://host.docker.internal:5002/alerts"
        send_resolved: true
