global:
  scrape_interval: 5s

rule_files:
  - /etc/prometheus/alerts.yml

scrape_configs:
  - job_name: "api"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["api:8001"]

  - job_name: "worker"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["worker:9101"]

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]